services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: printdb
      POSTGRES_USER: printuser
      POSTGRES_PASSWORD: printpass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  fastapi:
    build: .
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "8501:8501"

  n8n:
    image: n8nio/n8n
    ports:
      - "5679:5678"
    env_file: .env
    volumes:
      - ./n8n/data:/home/node/.n8n

volumes:
  pgdata: